# Generated by Django 4.2.16 on 2024-11-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='success_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
