# Generated by Django 4.2.16 on 2024-11-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_shortenedurl_access_count_shortenedurl_success_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='unique_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='URLAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('is_unique', models.BooleanField(default=False)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='shortener.shortenedurl')),
            ],
        ),
    ]
